package shadow.parser;

import shadow.parser.javacc.*;

public abstract class AbstractASTVisitor implements ShadowParserVisitor {

	protected Object data;
	
	public Object getData() {
		return data;
	}
	
	  abstract public Object visit(SimpleNode node, Object data) throws ShadowException;
	  abstract public Object visit(ASTCompilationUnit node, Object data);
	  abstract public Object visit(ASTPackageDeclaration node, Object data);
	  abstract public Object visit(ASTImportDeclaration node, Object data);
	  abstract public Object visit(ASTModifiers node, Object data);
	  abstract public Object visit(ASTTypeDeclaration node, Object data);
	  abstract public Object visit(ASTViewDeclaration node, Object data);
	  abstract public Object visit(ASTClassOrInterfaceDeclaration node, Object data);
	  abstract public Object visit(ASTExtendsList node, Object data);
	  abstract public Object visit(ASTImplementsList node, Object data);
	  abstract public Object visit(ASTEnumDeclaration node, Object data);
	  abstract public Object visit(ASTEnumBody node, Object data);
	  abstract public Object visit(ASTEnumConstant node, Object data);
	  abstract public Object visit(ASTTypeParameters node, Object data);
	  abstract public Object visit(ASTTypeParameter node, Object data);
	  abstract public Object visit(ASTTypeBound node, Object data);
	  abstract public Object visit(ASTClassOrInterfaceBody node, Object data);
	  abstract public Object visit(ASTClassOrInterfaceBodyDeclaration node, Object data);
	  abstract public Object visit(ASTFieldDeclaration node, Object data);
	  abstract public Object visit(ASTVariableDeclarator node, Object data);
	  abstract public Object visit(ASTVariableDeclaratorId node, Object data);
	  abstract public Object visit(ASTVariableInitializer node, Object data);
	  abstract public Object visit(ASTArrayInitializer node, Object data);
	  abstract public Object visit(ASTMethodDeclaration node, Object data);
	  abstract public Object visit(ASTMethodDeclarator node, Object data);
	  abstract public Object visit(ASTFormalParameters node, Object data);
	  abstract public Object visit(ASTFormalParameter node, Object data);
	  abstract public Object visit(ASTConstructorDeclaration node, Object data);
	  abstract public Object visit(ASTExplicitConstructorInvocation node, Object data);
	  abstract public Object visit(ASTInitializer node, Object data);
	  abstract public Object visit(ASTType node, Object data);
	  abstract public Object visit(ASTReferenceType node, Object data);
	  abstract public Object visit(ASTStaticArrayType node, Object data);
	  abstract public Object visit(ASTFunctionType node, Object data);
	  abstract public Object visit(ASTClassOrInterfaceType node, Object data);
	  abstract public Object visit(ASTTypeArguments node, Object data);
	  abstract public Object visit(ASTTypeArgument node, Object data);
	  abstract public Object visit(ASTWildcardBounds node, Object data);
	  abstract public Object visit(ASTPrimitiveType node, Object data);
	  abstract public Object visit(ASTResultType node, Object data);
	  abstract public Object visit(ASTResultTypes node, Object data);
	  abstract public Object visit(ASTName node, Object data);
	  abstract public Object visit(ASTNameList node, Object data);
	  abstract public Object visit(ASTExpression node, Object data);
	  abstract public Object visit(ASTAssignmentOperator node, Object data);
	  abstract public Object visit(ASTConditionalExpression node, Object data);
	  abstract public Object visit(ASTConditionalOrExpression node, Object data);
	  abstract public Object visit(ASTConditionalAndExpression node, Object data);
	  abstract public Object visit(ASTInclusiveOrExpression node, Object data);
	  abstract public Object visit(ASTExclusiveOrExpression node, Object data);
	  abstract public Object visit(ASTAndExpression node, Object data);
	  abstract public Object visit(ASTEqualityExpression node, Object data);
	  abstract public Object visit(ASTInstanceOfExpression node, Object data);
	  abstract public Object visit(ASTRelationalExpression node, Object data);
	  abstract public Object visit(ASTShiftExpression node, Object data);
	  abstract public Object visit(ASTRotateExpression node, Object data);
	  abstract public Object visit(ASTAdditiveExpression node, Object data);
	  abstract public Object visit(ASTMultiplicativeExpression node, Object data);
	  abstract public Object visit(ASTUnaryExpression node, Object data);
	  abstract public Object visit(ASTUnaryExpressionNotPlusMinus node, Object data);
	  abstract public Object visit(ASTCastExpression node, Object data);
	  abstract public Object visit(ASTPrimaryExpression node, Object data);
	  abstract public Object visit(ASTMemberSelector node, Object data);
	  abstract public Object visit(ASTPrimaryPrefix node, Object data);
	  abstract public Object visit(ASTPrimarySuffix node, Object data);
	  abstract public Object visit(ASTLiteral node, Object data);
	  abstract public Object visit(ASTBooleanLiteral node, Object data);
	  abstract public Object visit(ASTNullLiteral node, Object data);
	  abstract public Object visit(ASTArguments node, Object data);
	  abstract public Object visit(ASTArgumentList node, Object data);
	  abstract public Object visit(ASTAllocationExpression node, Object data);
	  abstract public Object visit(ASTArrayDimsAndInits node, Object data);
	  abstract public Object visit(ASTStatement node, Object data);
	  abstract public Object visit(ASTAssertStatement node, Object data);
	  abstract public Object visit(ASTLabeledStatement node, Object data);
	  abstract public Object visit(ASTBlock node, Object data);
	  abstract public Object visit(ASTBlockStatement node, Object data);
	  abstract public Object visit(ASTLocalVariableDeclaration node, Object data);
	  abstract public Object visit(ASTEmptyStatement node, Object data);
	  abstract public Object visit(ASTStatementExpression node, Object data);
	  abstract public Object visit(ASTSwitchStatement node, Object data);
	  abstract public Object visit(ASTSwitchLabel node, Object data);
	  abstract public Object visit(ASTIfStatement node, Object data);
	  abstract public Object visit(ASTWhileStatement node, Object data);
	  abstract public Object visit(ASTDoStatement node, Object data);
	  abstract public Object visit(ASTForeachStatement node, Object data);
	  abstract public Object visit(ASTForStatement node, Object data);
	  abstract public Object visit(ASTForInit node, Object data);
	  abstract public Object visit(ASTStatementExpressionList node, Object data);
	  abstract public Object visit(ASTForUpdate node, Object data);
	  abstract public Object visit(ASTBreakStatement node, Object data);
	  abstract public Object visit(ASTContinueStatement node, Object data);
	  abstract public Object visit(ASTReturnStatement node, Object data);
	  abstract public Object visit(ASTThrowStatement node, Object data);
	  abstract public Object visit(ASTSynchronizedStatement node, Object data);
	  abstract public Object visit(ASTTryStatement node, Object data);
	  abstract public Object visit(ASTRIGHTROTATE node, Object data);
	  abstract public Object visit(ASTRIGHTSHIFT node, Object data);
	  abstract public Object visit(ASTMemberValuePairs node, Object data);
	  abstract public Object visit(ASTMemberValuePair node, Object data);
	  abstract public Object visit(ASTMemberValue node, Object data);
	  abstract public Object visit(ASTMemberValueArrayInitializer node, Object data);
	  abstract public Object visit(ASTDefaultValue node, Object data);
}
