/* Generated By:JJTree: Do not edit this line. ASTArrayDimensions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTArrayDimensions extends DimensionNode {
  public ASTArrayDimensions(int id) {
    super(id);
  }

  public ASTArrayDimensions(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb117e9db8c030a58d1ffd7fda85bb1f (do not edit this line) */
