/* Generated By:JJTree: Do not edit this line. ASTCreateDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTCreateDeclaration extends SignatureNode {
	
	private boolean hasExplicitCreate = false;
	
	
  public ASTCreateDeclaration(int id) {
    super(id);
  }

  public ASTCreateDeclaration(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
  
  
  public void setExplicitCreate(boolean value) {
	  hasExplicitCreate = value;	  
  }
  
  public boolean hasExplicitCreate() {
	  return hasExplicitCreate;
  }  
  
}
/* JavaCC - OriginalChecksum=f9765d6dc3453eb835131eea80f8e3a0 (do not edit this line) */
