/* Generated By:JJTree: Do not edit this line. ASTForeachInit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

import shadow.tac.TACVariable;
import shadow.typecheck.type.Type;

public
class ASTForeachInit extends SimpleNode {

	private TACVariable variable;
	private Type collectionType;
	
	public void setCollectionType(Type type)
	{
		collectionType = type;
	}
	
	public Type getCollectionType()
	{
		return collectionType;
	}
	
	public void setVariable(TACVariable variable)
	{
		this.variable = variable;
	}
	
	public TACVariable getVariable()
	{
		return variable;		
	}
	
	
  public ASTForeachInit(int id) {
    super(id);
  }

  public ASTForeachInit(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5c44f8acdfecaa6b51ffc396e27b57f0 (do not edit this line) */
