/* Generated By:JJTree: Do not edit this line. ASTGenericDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public class ASTGenericDeclaration extends SimpleNode {
  public ASTGenericDeclaration(int id) {
    super(id);
  }
  
  public ASTGenericDeclaration(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3b7c056b59edf69fe311dd70639e51b (do not edit this line) */
