/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

import java.util.ArrayList;
import java.util.List;

import shadow.tac.nodes.TACLabel;
import shadow.tac.nodes.TACOperand;

public
@SuppressWarnings("all")
class ASTSwitchLabel extends SimpleNode {
	
	private List<TACOperand> values = new ArrayList<TACOperand>();
	private TACLabel label;
	
	public TACLabel getLabel()
	{
		return label;
	}
	
	public void setLabel(TACLabel label)
	{
		this.label = label;
	}
	
	
	public void addValue(TACOperand value)
	{
		values.add(value);
	}
	
	public List<TACOperand> getValues()
	{
		return values;
	}
	
	public boolean isDefault()
	{
		return jjtGetNumChildren() == 0;
	}
	
  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
}
/* JavaCC - OriginalChecksum=ce2230732353230518898089bf84bc0b (do not edit this line) */
