/* Generated By:JJTree: Do not edit this line. ASTVersion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package shadow.parser.javacc;

public class ASTVersion extends SimpleNode {
  public ASTVersion(int id) {
    super(id);
  }

  public ASTVersion(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
}
/* JavaCC - OriginalChecksum=fa5294a673ed300e1135f6f21c51b73a (do not edit this line) */
