/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceTypeSuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

import java.util.List;

import shadow.typecheck.type.TypeParameter;

public
@SuppressWarnings("all")
class ASTClassOrInterfaceTypeSuffix extends SimpleNode {	

	private List<TypeParameter> parameters = null;	
	
  public ASTClassOrInterfaceTypeSuffix(int id) {
    super(id);
  }

  public ASTClassOrInterfaceTypeSuffix(ShadowParser p, int id) {
    super(p, id);
  }  
  
  
  public void setParameters(List<TypeParameter> parameters)
  {
	  this.parameters = parameters;
  }
  
  public List<TypeParameter> getParameters()
  {
	  return parameters;
  }
  

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=965342435b53e322b0b86f167eb46ad2 (do not edit this line) */
