/* Generated By:JJTree: Do not edit this line. ASTFinallyStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTFinallyStatement extends SimpleNode {
  public ASTFinallyStatement(int id) {
    super(id);
  }

  public ASTFinallyStatement(ShadowParser p, int id) {
    super(p, id);
  }


  public boolean hasFinally() {
    return jjtGetNumChildren() == 2;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48cad04696871387db18519daa41de95 (do not edit this line) */
