/* Generated By:JJTree: Do not edit this line. ASTQualifiedKeyword.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTQualifiedKeyword extends SimpleNode {
  public ASTQualifiedKeyword(int id) {
    super(id);
  }  

  public ASTQualifiedKeyword(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b8fcdc8972995f39dd8fc6c79d53a424 (do not edit this line) */
