/* Generated By:JJTree: Do not edit this line. ASTSequenceLeftSide.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

import java.util.LinkedList;

public
@SuppressWarnings("all")
class ASTSequenceLeftSide extends SequenceNode {
  public ASTSequenceLeftSide(int id) {
    super(id);
  }

  public ASTSequenceLeftSide(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
  
  private LinkedList<Boolean> usedItems = new LinkedList<Boolean>();
  
  public void addItem()
  {
	  usedItems.add(false);
  }
  
  public void setUsed()
  {
	  if( !usedItems.isEmpty())
		  usedItems.set(usedItems.size() - 1, true);
  }
  
  public LinkedList<Boolean> getUsedItems()
  {
	  return usedItems;
  }
  
}
/* JavaCC - OriginalChecksum=65d5cb8f590493a7efdf5837372a7ee0 (do not edit this line) */
