/* Generated By:JJTree: Do not edit this line. ASTViewBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTViewBodyDeclaration extends SimpleNode {
  public ASTViewBodyDeclaration(int id) {
    super(id);
  }

  public ASTViewBodyDeclaration(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f1cb5ba4129f4bbc1a5fb866b2ae3a54 (do not edit this line) */
