/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTAnnotationTypeDeclaration extends SimpleNode {
  public ASTAnnotationTypeDeclaration(int id) {
    super(id);
  }

  public ASTAnnotationTypeDeclaration(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7a1d37361c7e784c810c4396a6f0c048 (do not edit this line) */
