/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
  
  public enum AssignmentType {
	  EQUAL,
	  PLUS,
	  MINUS,
	  STAR,
	  SLASH,
	  AND,
	  OR,
	  XOR,
	  MOD,
	  CAT,
	  LEFT_SHIFT,
	  RIGHT_SHIFT,
	  RIGHT_ROTATE,
	  LEFT_ROTATE
  }
  
  protected AssignmentType assignmentType;
  
  public void setAssignmentType(AssignmentType type) {
	this.assignmentType = type;  
  }
  
  public AssignmentType getAssignmentType() {
	  return this.assignmentType;
  }
}
/* JavaCC - OriginalChecksum=92708bdf2f854aa06c093a0c5cea3295 (do not edit this line) */
