/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public enum AssignmentType {
	  EQUAL,
	  PLUSASSIGN,
	  MINUSASSIGN,
	  STARASSIGN,
	  SLASHASSIGN,
	  ANDASSIGN,
	  ORASSIGN,
	  XORASSIGN,
	  REMASSIGN,
	  REFASSIGN,
	  LEFTSHIFTASSIGN,
	  RIGHTSHIFTASSIGN,
	  RIGHTROTATEASSIGN,
	  LEFTROTATEASSIGN
  }
  
  protected AssignmentType type;
  
  public void setAssignmentType(AssignmentType type) {
	this.type = type;  
  }
}
/* JavaCC - OriginalChecksum=92708bdf2f854aa06c093a0c5cea3295 (do not edit this line) */
