/* Generated By:JJTree: Do not edit this line. ASTBrackets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;


public
@SuppressWarnings("all")
class ASTBrackets extends DimensionNode {
  public ASTBrackets(int id) {
    super(id);
  }

  public ASTBrackets(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
  
  
  
}
/* JavaCC - OriginalChecksum=f2840da10c95748dabf39f047a2d1906 (do not edit this line) */
