/* Generated By:JJTree: Do not edit this line. ASTBitwiseExclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTBitwiseExclusiveOrExpression extends OperationNode {
  public ASTBitwiseExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTBitwiseExclusiveOrExpression(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
}
/* JavaCC - OriginalChecksum=97a7b1d7b3366c0b799fa189c23cf37d (do not edit this line) */
