/* Generated By:JJTree: Do not edit this line. ASTConcatenationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTConcatenationExpression extends SimpleNode {
  public ASTConcatenationExpression(int id) {
    super(id);
  }

  public ASTConcatenationExpression(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a6e9c5aa44c013c1c60c2d549db9d09 (do not edit this line) */
