/* Generated By:JJTree: Do not edit this line. ASTCatchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTCatchStatement extends SimpleNode {
  public ASTCatchStatement(int id) {
    super(id);
  }

  public ASTCatchStatement(ShadowParser p, int id) {
    super(p, id);
  }

//comment
  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2bb6f24c25e9235a7ebf90b7aedd58cb (do not edit this line) */
