/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTClassOrInterfaceDeclaration extends SimpleNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) throws ShadowException {
    return visitor.visit(this, data);
  }
  
  int modifiers;
  
  public void setModifiers(int modifiers) {
	  this.modifiers = modifiers;
  }
}
/* JavaCC - OriginalChecksum=2cf34475db707e32cc511aa02d222848 (do not edit this line) */
