/* Generated By:JJTree: Do not edit this line. ASTCoalesceExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTCoalesceExpression extends SimpleNode {
  public ASTCoalesceExpression(int id) {
    super(id);
  }

  public ASTCoalesceExpression(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb4b25118555792bf33146d3cd2c08e4 (do not edit this line) */
