/* Generated By:JJTree: Do not edit this line. ASTDestructorDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTDestructorDeclaration extends SimpleNode {
  public ASTDestructorDeclaration(int id) {
    super(id);
  }

  public ASTDestructorDeclaration(ShadowParser p, int id) {
    super(p, id);
  }
  
  int modifiers;
  
  public int getModifiers() {
	  return modifiers;
  }
  
  public void setModifiers(int modifiers) {
	  this.modifiers = modifiers;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0027bed83cb4bbff32f4c80c24acaf3 (do not edit this line) */
