/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructInvocation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTExplicitConstructInvocation extends SimpleNode {
  public ASTExplicitConstructInvocation(int id) {
    super(id);
  }

  public ASTExplicitConstructInvocation(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7c3efcaf32a116d5ec8f6d434e453482 (do not edit this line) */
