/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

import java.util.ArrayList;
import java.util.List;

import shadow.typecheck.type.ModifiedType;
import shadow.typecheck.type.SequenceType;

public
@SuppressWarnings("all")
class ASTFormalParameters extends SequenceNode {
		
	private boolean local = false;
	
	public boolean isLocal()
	{
		return local;
	}
	
	public void setLocal(boolean value)
	{
		local = value;
	}
	
	  private List<String> parameterNames = new ArrayList<String>(); /** List of parameter names */  
		
		public List<String> getParameterNames() 
		{
			return parameterNames;
		}
		
		public void addParameter(String name, ModifiedType type) 
		{
			SequenceType parameterTypes = getType();		
			
			parameterNames.add(name);
			parameterTypes.add(type);
		}

	
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(ShadowParser p, int id) {
    super(p, id);    
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
}
/* JavaCC - OriginalChecksum=6ea629aa6ebac837ef53db611da45f4a (do not edit this line) */
