/* Generated By:JJTree: Do not edit this line. ASTInlineMethodDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTInlineMethodDefinition extends SignatureNode {
  public ASTInlineMethodDefinition(int id) {
    super(id);
  }

  public ASTInlineMethodDefinition(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fbdce77ed76ecb50b3ba5c7362d33be2 (do not edit this line) */
