/* Generated By:JJTree: Do not edit this line. ASTInlineMethodDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTInlineMethodDeclarator extends SimpleNode {
  public ASTInlineMethodDeclarator(int id) {
    super(id);
  }

  public ASTInlineMethodDeclarator(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1f59a4d0a3a6dfd26dfe73187e3d573d (do not edit this line) */
