/* Generated By:JJTree: Do not edit this line. ASTInnerTryStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTInnerTryStatement extends SimpleNode
{	
	private int catches = 0;
	private boolean recover = false;
	
	public void addCatch()
	{
		catches++;		
	}
	
	public void addRecover()
	{
		recover = true;				
	}
	
	public int getCatches()
	{
		return catches;
	}
	
	public boolean hasCatches()
	{
		return catches != 0;
	}
	
	
	public boolean hasRecover()
	{
		return recover;
	}	
	
	
  public ASTInnerTryStatement(int id) {
    super(id);
  }

  public ASTInnerTryStatement(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor.  **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0228182bbfe83151ec530abba6800df6 (do not edit this line) */
