/* Generated By:JJTree: Do not edit this line. ASTLocalMethodDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTLocalMethodDeclaration extends SignatureNode {
  public ASTLocalMethodDeclaration(int id) {
    super(id);
  }

  public ASTLocalMethodDeclaration(ShadowParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=568bdcce5aabca0ceb57c39db01cf676 (do not edit this line) */
