/* Generated By:JJTree: Do not edit this line. ASTMarkerAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTMarkerAnnotation extends SimpleNode {
  public ASTMarkerAnnotation(int id) {
    super(id);
  }

  public ASTMarkerAnnotation(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3847863f7dc8b15fee50820e08877669 (do not edit this line) */
