/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6fe33dbba25cbb3d4835692e92bc3760 (do not edit this line) */
