/* Generated By:JJTree: Do not edit this line. ASTNormalAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTNormalAnnotation extends SimpleNode {
  public ASTNormalAnnotation(int id) {
    super(id);
  }

  public ASTNormalAnnotation(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1f3566e807c8de512e68a071df24c4bd (do not edit this line) */
