/* Generated By:JJTree: Do not edit this line. ASTQualifiedSuper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTQualifiedSuper extends SimpleNode {
  public ASTQualifiedSuper(int id) {
    super(id);
  }

  public ASTQualifiedSuper(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=342b10737238d3b1219aa94fc97bfde0 (do not edit this line) */
