/* Generated By:JJTree: Do not edit this line. ASTRecoverStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTRecoverStatement extends SimpleNode {
	
	
	private boolean recover = false;
	
	public void addRecover()
	{
		recover = true;		
	}
	
	public boolean hasRecover()
	{
		return recover;		
	}
	
  public ASTRecoverStatement(int id) {
    super(id);
  }

  public ASTRecoverStatement(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a7df3a62154c82f27b6b8e94bd2dc16 (do not edit this line) */
