/* Generated By:JJTree: Do not edit this line. ASTRIGHTROTATE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTRIGHTROTATE extends SimpleNode {
  public ASTRIGHTROTATE(int id) {
    super(id);
  }

  public ASTRIGHTROTATE(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Object data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6aad06db80520df04fba293c8a037dd8 (do not edit this line) */
