/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTSwitchStatement extends SimpleNode {

	private boolean hasDefault = false;
	
	public void setDefault(boolean value)
	{
		hasDefault = value;
	}
	
	public boolean hasDefault()
	{
		return hasDefault;
	}
	
  public ASTSwitchStatement(int id) {
    super(id);
  }

  public ASTSwitchStatement(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
}
/* JavaCC - OriginalChecksum=7f5efd1246bf42449f0f922baaf9dd82 (do not edit this line) */
