/* Generated By:JJTree: Do not edit this line. ASTScopeSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTScopeSpecifier extends SimpleNode {
  public ASTScopeSpecifier(int id) {
    super(id);
  }

  public ASTScopeSpecifier(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b00b253c4b138fe9f3bb731d3036f3f (do not edit this line) */
