/* Generated By:JJTree: Do not edit this line. ASTSequenceAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
class ASTSequenceAssignment extends SimpleNode {
  public ASTSequenceAssignment(int id) {
    super(id);
  }

  public ASTSequenceAssignment(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4ca72b20e5dc7f42d54fa9e8e85bc2a3 (do not edit this line) */
