/* Generated By:JJTree: Do not edit this line. ASTUnaryToString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTUnaryToString extends SimpleNode {
  public ASTUnaryToString(int id) {
    super(id);
  }

  public ASTUnaryToString(ShadowParser p, int id) {
    super(p, id);
  }

  
  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean data) throws ShadowException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c971eecb7c7a8fac1864401bb456692 (do not edit this line) */
