/* Generated By:JJTree: Do not edit this line. ASTViewDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package shadow.parser.javacc;

public
@SuppressWarnings("all")
class ASTViewDeclaration extends SimpleNode {
  public ASTViewDeclaration(int id) {
    super(id);
  }

  public ASTViewDeclaration(ShadowParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ShadowParserVisitor visitor, Boolean secondVisit) throws ShadowException {
    return visitor.visit(this, secondVisit);
  }
  
  private int modifiers;
  
  public void setModifiers(int modifiers) {
	  this.modifiers = modifiers;
  }
  
  public int getModifiers() {
	  return this.modifiers;
  }
}
/* JavaCC - OriginalChecksum=2e8a6a7ac62762bc3e25bf5d36b7216e (do not edit this line) */
